### ISSUE TITLE
Feature: beaconcha.in stats

### ISSUE THREAD

**Issue by yorickdowne** [sifraitech/grandine#10]
Stat collection is useful for solo stakers, where the CL will send statistics to an API endpoint for alerting via a phone app.

See https://beaconcha.in/user/settings#app

**Comment by sauliusgrigaitis** [comment]
We have it https://grandine.io/metrics.html#remote-metrics . Let us know if you have any issue with this feature.

**Comment by yorickdowne** [comment]
Thanks!
