### ISSUE TITLE
Feature: Support Doppelganger detection on VC

### ISSUE THREAD

**Issue by yorickdowne** [sifraitech/grandine#11]
Support doppelganger detection in some fashion for keys loaded into Grandine.

Definitely not urgent; could make sense after a standalone VC exists and is stable.

**Comment by sauliusgrigaitis** [comment]
We probably will get this feature before standalone VC. Standalone VC will take some time really.

**Comment by Tumas** [comment]
Hey, @yorickdowne  Doppelganger support has been added recently with 92e08abafb08feb733f094e0fcfaa6d694db68e9

**Comment by Tumas** [comment]
I’m closing this issue as the requested functionality was implemented some time ago, and no further updates or activity have occurred since. If there are any additional concerns or related needs, please feel free to reopen this issue or create a new one.
