### ISSUE TITLE
Change tagline to from eth2 to CL

### ISSUE THREAD

**Issue by taxmeifyoucan** [sifraitech/grandine#14]
The current repository description describes the project as 'The Fastest Ethereum 2.0 Client' which is using old eth2 nomenclature and can be quite confusing. The correct naming should be a 'Consensus client' or 'Consensus layer client'. This is the most significant reference I noticed so far but if there are others, consider updating it too. 

Btw congrats on going FOSS with GPL!

**Comment by sauliusgrigaitis** [comment]
Fixed, thanks :)
