### ISSUE TITLE
Move slashing protection DB to validator dir

### ISSUE THREAD

**Issue by yorickdowne** [sifraitech/grandine#22]
Currently `slashing_protection.sqlite` is in `beacon`. This is un-intuitive and can lead to slashing when a user resyncs the beacon by stopping it, removing the contents of `beacon` and starting again, depending on how fast the resync from checkpoint is.

Placing it into `validator` is in line with what other clients do, and makes sense logically, since it's the validator that's being protected from slashing.

**Comment by sauliusgrigaitis** [comment]
We should also copy `slashing_protection.sqlite` from `beacon` to `validator` if we don't find `slashing_protection.sqlite` in `validator` dir.

**Comment by yorickdowne** [comment]
Thanks for getting that done!
