### ISSUE TITLE
Add active peercount in the log messages

### ISSUE THREAD

**Issue by barnabasbusa** [sifraitech/grandine#30]
A very basic debug step is ensuring that a client has sufficient amount of peers.

Printing the number of active peers would be very helpful.

**Comment by varun-doshi** [comment]
Can I take this?

**Comment by Tumas** [comment]
hey @barnabasbusa , did you have the chance to test this? Fix has been merged to develop & electra.

**Comment by barnabasbusa** [comment]
LGTM
