### ISSUE TITLE
Feature: SSE - emit slashing events

### ISSUE THREAD

**Issue by eth2353** [sifraitech/grandine#36]
It would be great if Grandine could add support for these SSE events ( `attester_slashing` , `proposer_slashing` ) so that validator clients can react quickly to slashing events by e.g. shutting down.

All other CL client implementations already emit these events.

Introduced in the Beacon API spec v2.5.0 - https://github.com/ethereum/beacon-APIs/releases/tag/v2.5.0

**Comment by Tumas** [comment]
Hey, @eth2353  support for slashing SSE events has been added to develop. Did you have the chance to test this?

**Comment by eth2353** [comment]
Thanks Tumas, appreciate it! I did not get an email notification for that commit, so I hadn't noticed.

I haven't figured out a good way to actually test this end-to-end, will probably need to play around with kurtosis and let you know how it went. Feel free to close this issue in the meantime.

**Comment by eth2353** [comment]
Hi @Tumas I have now tested both of these SSE events using Kurtosis and both work well, thanks for this!
