### ISSUE TITLE
Implement query filters on beacon API endpoint /eth/v1/node/peers

### ISSUE THREAD

**Issue by skylenet** [sifraitech/grandine#46]
As per API spec https://ethereum.github.io/beacon-APIs/#/Node/getPeers

There are some filters that one can provide via URL query params: `state` and `direction`. 

Currently they don't seem to be implemented.

With the following example I would expect to just get a filtered list of peers that have `state=connected`:

```
/eth/v1/node/peers?state=connected
```

**Comment by Tumas** [comment]
Hey @skylenet, this should be working now as expected.

**Comment by Tumas** [comment]
@skylenet did you have the chance to test this? Feel free to close this issue if there are no more issues with this.
