### ISSUE TITLE
Add missing field `el_offline` for interop with lighthouse validator client >= v5.3.0

### ISSUE THREAD

**Issue by laibe** [sifraitech/grandine#49]
Latest grandine stable release (0.4.1) is no longer compatible with lighthouse validator client (>= v5.3.0) since they expect `el_offline`. Relevant change on lighthouse that removed the backwards compatibility: 

https://github.com/sigp/lighthouse/commit/a3f44c674b070ec3b131f4fe9482f3b1f8b90bbe

**Comment by Tumas** [comment]
I’m closing this issue as the requested functionality was implemented some time ago, and no further updates or activity have occurred since. If there are any additional concerns or related needs, please feel free to reopen this issue or create a new one.
