### ISSUE TITLE
ENR udp port 43619?

### ISSUE THREAD

**Issue by totoCZ** [sifraitech/grandine#63]
Standard config like
Built from git 1ce3083aedcc85cef7e789a0805dcd38c74bc0f3 

>--http-address :: 
>--listen-address-ipv6 :: 
>--libp2p-port 30304 
>--libp2p-port-ipv6 30304 
>--discovery-port 30305 
>--discovery-port-ipv6 30305 
>--quic-port 30306 
>--quic-port-ipv6 30306 

>"discovery_addresses":["/ip4/***********/udp/43619/p2p/16Uiu2HAmAydS9Y1FPEvAKueuTxD6VNKCi3KnD63RaktAU9DcFbNz"],

43619

Shouldn't it be one of those? 30304, I think?

I also found out it doesn't advertise v6 unless I set 

--enr-address-ipv6

**Comment by totoCZ** [comment]
```
Listening ports in container 'systemd-grandine':
---------------------------------
Proto Local Address           Port
tcp   0.0.0.0               30304
tcp6  ::                    30304
tcp6  ::                    5054
tcp6  ::                    5052
udp   0.0.0.0               30305
udp   0.0.0.0               30306
udp6  ::                    30305
udp6  ::                    30306

```

So it should be 30305 (discv5). Correct me if I'm wrong.

Testing with API

```
curl -X 'GET' \
      'http://**********:5052/eth/v1/node/identity' \
      -H 'accept: application/json'
```

**Comment by totoCZ** [comment]
It's correctly set in "unstable" but I also added enr-udp-port etc. So maybe double check if it works on the master.

**Comment by sauliusgrigaitis** [comment]
@totoCZ we are planning for the stable 1.0 release in January. Until then I suggest using "unstable".
