### ISSUE TITLE
Feature: Multi-architecture docker images

### ISSUE THREAD

**Issue by yorickdowne** [sifraitech/grandine#7]
Instead of `latest` and `latest-arm64,` have a single image that supports both amd64 and arm64. This makes integration of Grandine with automation frameworks like eth-docker considerably easier.

**Comment by sauliusgrigaitis** [comment]
Thanks, will try to get this in the next release. We already build with `docker buildx` so should not be a bit change of the pipeline.

**Comment by sauliusgrigaitis** [comment]
Done. Can be tested by running `docker run sifrai/grandine:latest grandine` both on `amd64` and `arm64`.
