### ISSUE TITLE
Feature: Support keymanager API

### ISSUE THREAD

**Issue by yorickdowne** [sifraitech/grandine#8]
Eth Docker uses the standard keymanager API to handle keys. As Grandine goes FOSS I'd like to offer support for it; this requires keymanager API to be present.

**Comment by sauliusgrigaitis** [comment]
Thanks for your support! Keymanager API is something that we will start to work on after we ship stable Deneb support.

**Comment by yorickdowne** [comment]
Excellent. MVP so I can merge the Grandine PR are `/eth/v1/keystores` and `/eth/v1/remotekeys` endpoints. Voluntary exit would be next after that. Fee recipient is good to have but not urgent; Gas limit and Graffiti are nice to have and definitely not urgent.

**Comment by sauliusgrigaitis** [comment]
@yorickdowne `0.4.0.rc4` has everything except voluntary exits. Please test.

**Comment by sauliusgrigaitis** [comment]
Seems no more issues with Keymanager API.
